const ACTIONS = {
    SET_WALLETS: 'SET_WALLETS',
    SETUP: 'SETUP',
    SET_TOKEN: 'SET_TOKEN',
    SET_PROFILE: 'SET_PROFILE',
    SET_CHAIN_ID: 'SET_CHAIN_ID',
    SET_PROVIDER: 'SET_PROVIDER',
    AUTHCHECK: 'AUTHCHECK',
    RESETAUTH: 'RESETAUTH',

    TRIGGER_CANDY_BALANCE: 'TRIGGER_CANDY_BALANCE',
    SET_CANDY_BALANCE: 'SET_CANDY_BALANCE',
};
export {ACTIONS};
