const ACTIONS = {
    TOGGLE_DRAWER: 'TOGGLE_DRAWER',
    SET_WALLETS: 'SET_WALLETS',
    SETUP: 'SETUP',
    SET_TOKEN: 'SET_TOKEN',
    SET_PROFILE: 'SET_PROFILE',
    SET_CHAIN_ID: 'SET_CHAIN_ID',
    SET_PROVIDER: 'SET_PROVIDER',
};
export {ACTIONS};
